/*
 * driver.h
 *
 *  Created on: Apr 4, 2014
 *      Author: RobG
 */

/*
 * Mods by Terje Io (added touch support etc)
 */

#pragma once

#define PORT2
#define MPGBOOSTERPACK

#define TOUCH_CS_PIN GPIO_PIN_2 // T_CS -> PE2
#define TOUCH_CS_PORT GPIO_PORTA_BASE
#define TOUCH_SELECT GPIO_PORTA_DATA_R &= ~TOUCH_CS_PIN
#define TOUCH_DESELECT GPIO_PORTA_DATA_R |= TOUCH_CS_PIN

#ifdef MPGBOOSTERPACK
#define LCD_SCLK_PIN GPIO_PIN_4 // SCK -> PB4
#define LCD_MOSI_PIN GPIO_PIN_7 // SDI (MOSI) -> PB7
#define LCD_MISO_PIN GPIO_PIN_6 // SDO (MISO) -> PB6

#define LCD_CS_PIN GPIO_PIN_3 // CS -> P3
#define LCD_CS_PORT GPIO_PORTD_BASE
#define LCD_SELECT GPIO_PORTD_DATA_R &= ~LCD_CS_PIN
#define LCD_DESELECT GPIO_PORTD_DATA_R |= LCD_CS_PIN

#define LCD_DC_PIN GPIO_PIN_5 // DC -> PA5
#define LCD_DC_PORT GPIO_PORTA_BASE
#define LCD_DC_CMD GPIO_PORTA_DATA_R &= ~LCD_DC_PIN
#define LCD_DC_DATA GPIO_PORTA_DATA_R |= LCD_DC_PIN

#define LCD_RESET_PIN GPIO_PIN_4 // RESET -> PF4
#define LCD_RESET_PORT GPIO_PORTF_BASE

#define SPI_PERIPH SYSCTL_PERIPH_SSI2
#define SPI_BASE SSI2_BASE
#define SPI_PORT GPIO_PORTB_BASE
#define SPI_DR SSI2_DR_R
#define SPI_SR SSI2_SR_R
#define SPI_CLK GPIO_PB4_SSI2CLK
#define SPI_TX GPIO_PB7_SSI2TX
#define SPI_RX GPIO_PB6_SSI2RX

#elif PORT2

#define LCD_SCLK_PIN GPIO_PIN_4 // SCK -> PB4
#define LCD_MOSI_PIN GPIO_PIN_7 // SDI (MOSI) -> PB7
#define LCD_MISO_PIN GPIO_PIN_6 // SDO (MISO) -> PB6

#define LCD_CS_PIN GPIO_PIN_1 // CS -> PE1
#define LCD_CS_PORT GPIO_PORTE_BASE
#define LCD_SELECT GPIO_PORTE_DATA_R &= ~LCD_CS_PIN
#define LCD_DESELECT GPIO_PORTE_DATA_R |= LCD_CS_PIN

#define LCD_DC_PIN GPIO_PIN_4 // DC -> PE4
#define LCD_DC_PORT GPIO_PORTE_BASE
#define LCD_DC_CMD GPIO_PORTE_DATA_R &= ~LCD_DC_PIN
#define LCD_DC_DATA GPIO_PORTE_DATA_R |= LCD_DC_PIN

#define SPI_PERIPH SYSCTL_PERIPH_SSI2
#define SPI_BASE SSI2_BASE
#define SPI_PORT GPIO_PORTB_BASE
#define SPI_DR SSI2_DR_R
#define SPI_SR SSI2_SR_R
#define SPI_CLK GPIO_PB4_SSI2CLK
#define SPI_TX GPIO_PB7_SSI2TX
#define SPI_RX GPIO_PB6_SSI2RX

#else

#define LCD_SCLK_PIN GPIO_PIN_2
#define LCD_MOSI_PIN GPIO_PIN_5 // TX
#define LCD_MISO_PIN GPIO_PIN_4 // RX

#define LCD_CS_PIN GPIO_PIN_0
#define LCD_CS_PORT GPIO_PORTA_BASE
#define LCD_SELECT GPIO_PORTA_DATA_R &= ~LCD_CS_PIN
#define LCD_DESELECT GPIO_PORTA_DATA_R |= LCD_CS_PIN

#define LCD_DC_PIN GPIO_PIN_1
#define LCD_DC_PORT GPIO_PORTA_BASE
#define LCD_DC_CMD GPIO_PORTA_DATA_R &= ~LCD_DC_PIN
#define LCD_DC_DATA GPIO_PORTA_DATA_R |= LCD_DC_PIN

#define SPI_PERIPH SYSCTL_PERIPH_SSI0
#define SPI_BASE SSI0_BASE
#define SPI_PORT GPIO_PORTA_BASE
#define SPI_DR SSI0_DR_R
#define SPI_SR SSI0_SR_R
#define SPI_CLK GPIO_PA2_SSI0CLK
#define SPI_TX GPIO_PA5_SSI0TX
#define SPI_RX GPIO_PA4_SSI0RX

#endif

#ifdef TOUCH_ENABLE

#define TOUCH_CS_PIN GPIO_PIN_2 // T_CS -> PE2
#define TOUCH_CS_PORT GPIO_PORTA_BASE
#define TOUCH_SELECT GPIO_PORTA_DATA_R &= ~TOUCH_CS_PIN
#define TOUCH_DESELECT GPIO_PORTA_DATA_R |= TOUCH_CS_PIN

#define TOUCH_IRQ_PIN GPIO_PIN_3 // T_IRQ -> PF1
#define TOUCH_IRQ_PORT GPIO_PORTA_BASE
#define TOUCH_IRQ_INT_PIN GPIO_INT_PIN_3
#define TOUCH_IRQ_PERIPH SYSCTL_PERIPH_GPIOA

#endif
